# -*- coding: utf-8 -*-
"""Q&A Web App.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lmkjQ44kwj7x9QBKwL_PCEtOIW1LnPAJ

**# Importing Depedencies**
"""

# Pytorch install :

!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

# Transformers install

! pip install transformers

""" **# Load Model**"""

# importing the depedencies for RoBERTa Model

from transformers import AutoModelForQuestionAnswering, AutoTokenizer, pipeline

# Creating the Q&A pipeline

nlp = pipeline('question-answering',model = 'deepset/roberta-base-squad2',tokenizer = 'deepset/roberta-base-squad2')

# Contextual text or corpus

context = """

        Iron Man is a superhero appearing in American comic books published by Marvel Comics. Co-created by writer and editor Stan Lee, developed by scripter Larry Lieber, and designed by artists Don Heck and Jack Kirby, the character first appeared in Tales of Suspense #39 in 1963, and received his own title with Iron Man #1 in 1968.
        Shortly after his creation, Iron Man was a founding member of a superhero team, the Avengers, with Thor, Ant-Man, Wasp and the Hulk.
        Iron Man stories, individually and with the Avengers, have been published consistently since the character's creation.
        Robert Downey Jr. portrayed Tony Stark in Iron Man (2008), the first film of the Marvel Cinematic Universe, and continued to portray the character until his final appearance in Avengers: Endgame (2019).
        Downey's portrayal popularized the character, elevating Iron Man as one of Marvel's most recognizable superheroes.

"""

# Define Question Set

question_set = {
          'question': 'Who designed Iron man?',
          'context' : context
}

results=nlp(question_set)

results['answer']

"""**# Connect to Anvil**"""

! pip install anvil-uplink

import anvil.server

anvil.server.connect('server_UXIS2VT42MJ2MMEWMBS4BA5C-Z3JC6CDRMZZVQO5Q')

"""**# Setup Callable Function**"""

# Tell the google colab server that this is an anvil callable function

@anvil.server.callable
# Define the function that is going to do our NLP
def answer_questions(question_text,input_text):
  # Convert it into a dictionary
     question_set = {
          'question': question_text,
          'context' : input_text
}

 # Run it through the nlp pipeline
     results = nlp(question_set)

     return results['answer']

anvil_result = answer_questions('Who designed Iron man?',context)

anvil_result